server:
    port: 8080

liquibase:
    context: prod

spring:
    profiles:
        active: prod
    data:
        mongodb:
            host: 192.168.0.24
            port: 27017
            database: mltrading
    thymeleaf:
        mode: XHTML
        cache: true

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: mltrading

http:
    cache:
        timeToLiveInDays: 31


